### ISSUE TITLE
Error when calling jenkis with python3 and no argument

### ISSUE THREAD

**Issue by LD250** [LD250/jenkins-cli-python#14]
with python 2.7

``` bash
$ jenkins
usage: jenkins [-h] [--host jenkins-url] [--username username]
               [--password password]
               {jobs,queue,building,start,info,set_branch,stop,console} ...
jenkins: error: too few arguments
```

with python 3 (I tried 3.4)

``` bash
$ jenkins
Traceback (most recent call last):
  File "/home/denis/.virtualenvs/jenkins-cli-py3/bin/jenkins", line 9, in <module>
    load_entry_point('jenkins-cli==0.1', 'console_scripts', 'jenkins')()
  File "/home/denis/.virtualenvs/jenkins-cli-py3/lib/python3.4/site-packages/jenkins_cli-0.1-py3.4.egg/jenkins_cli/__init__.py", line 49, in main
    JenkinsCli(args).run_command(args)
  File "/home/denis/.virtualenvs/jenkins-cli-py3/lib/python3.4/site-packages/jenkins_cli-0.1-py3.4.egg/jenkins_cli/cli.py", line 64, in run_command
    getattr(self, command)(args)
TypeError: getattr(): attribute name must be string
```

looks like argparse change it's behavior. It does not print "too few arguments" with help message anymore

**Comment by LD250** [comment]
@bcicen , got this issue after merge PR #13. I believe the same is for python 3.5.

**Comment by bcicen** [comment]
When installing as a package, `getcwd()` will return the package path(/usr/lib/python..) instead of the current directory of the user calling jenkins.

Perhaps we should look for the config file in the users home dir(`/home/user/.jenkins`) always instead?

**Comment by LD250** [comment]
> Perhaps we should look for the config file in the users home dir(/home/user/.jenkins) always instead

I create separate issue #15.
Please check it.

**Comment by bcicen** [comment]
Great; looks good!

**Comment by radomirbosak** [comment]
Is this still an issue? Could not reproduce this behaviour on Fedora 25 with Python 3.5.3 and everything is working fine for me:
```console
$ python3 --version
Python 3.5.3
$ pip3 install --user .
...
$ jenkins
usage: jenkins [-h] [--host jenkins-url] [--username username]
               [--password password] [--version]
               {jobs,queue,building,builds,start,info,setbranch,stop,console,changes}
               ...

Host, username and password may be specified either by the command line
...
```

The result was the same with `sudo pip3 install .` .

**Comment by LD250** [comment]
Yes, I think this can be closed

**Comment by radomirbosak** [comment]
Why was this reopened? Does the bug still happen? I can try with python3.4 if needed

**Comment by LD250** [comment]
I think this was reopened by accident. Will close it now.
