### ISSUE TITLE
version property in setup.py

### ISSUE THREAD

**Issue by LD250** [LD250/jenkins-cli-python#16]
Hi @bcicen , I have to figure for myself, what is the benefit of providing version in separate file (version.py in our case)? Can you please explain it to me.

**Comment by bcicen** [comment]
@LD250 it allows you to set the version using the same variable in both setup.py and within the package(if, say, you wanted to add a `--version` flag to jenkins-cli in the future) without import errors(from the dependent packages that haven't yet been installed).

**Comment by LD250** [comment]
Thank you. Now it's clear to me.
