### ISSUE TITLE
Error when runnign tests with python3.5 on Travis

### ISSUE THREAD

**Issue by LD250** [LD250/jenkins-cli-python#29]
https://travis-ci.org/LD250/jenkins-cli-python/jobs/231733557

> pkg_resources.VersionConflict: (pbr 1.10.0 (/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages), Requirement.parse('pbr>=2.0.0'))

**Comment by radomirbosak** [comment]
Is this still a problem? I just ran a travis test with this file:

```console
$ cat .travis.yml
language: "python"
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
install:
    - pip install flake8 mock==2.0.0
script:
    - flake8 
    - python setup.py test
```
and the job passed just fine. I'll follow up with a PR
