### ISSUE TITLE
Add a --conf CLI argument to specify different config file

### ISSUE THREAD

**Issue by radomirbosak** [LD250/jenkins-cli-python#33]
`--conf`is used also in [jenkins job builder](https://github.com/openstack-infra/jenkins-job-builder) for specifying config files.

So
```
$ jenkins jobs
```
would do the same as 
```
$ jenkins --conf ~/.jenkins-cli jobs
```

Being able to specify a different config file is beneficial when you work with multiple Jenkins instances.

**Comment by LD250** [comment]
You can run script from directory where you have ```.jenkins-cli```. So you can specify  jenkins settings in ```.jenkins-cli``` file on project level. Does it work for you?

**Comment by radomirbosak** [comment]
A `.jenkins-cli` file in the current directory of course works, but it's not optimal for the workflow that I use. 

I wanted to have three config files for three jenkins instances in the same directory and be able to switch between them easily
```console
$ cd myjenkinsdir
$ ls
job_definitions/  prod  qa  stage

$ jenkins jobs -c prod
S.. first-job
F.. private-unit-test

$ jenkins jobs -c stage
S.. some-other-job
F.. refresh-something
```

Or maybe even better would be (and this is different than what I proposed originally) if the config file allowed for multiple instances using config file sections, e.g.:
```console
$ cat ~/.jenkins-cli
[local]
host=http://localhost:8080/
username=rado
password=mypassword

[stage]
host=http://jenkins-stage.example.com/
username=rado
password=myotherpassword

[prod]
host=http://jenkins-prod.example.com/
username=produser
password=mydifferentpassword
```
And then use
```console
$ jenkins jobs --instance prod
```
or simply
```console
$ jenkins jobs -i prod
```

What do you think about this? Do you think it would be an enhancement worth implementing?

**Comment by radomirbosak** [comment]
I moved this second proposal to a separate issue https://github.com/LD250/jenkins-cli-python/issues/36

**Comment by LD250** [comment]
Hello @radomirbosak .
As #36 is resolved, do you think we still need ```--conf ~/.jenkins-cli``` option?

**Comment by radomirbosak** [comment]
I don't think we need this anymore. Let me close this issue.
