### ISSUE TITLE
Cannot install the package to user's home

### ISSUE THREAD

**Issue by radomirbosak** [LD250/jenkins-cli-python#37]
How to reproduce:
```console
$ pip3 install --user .
Processing /home/rbosak/frepos/jenkins-cli-python
Requirement already satisfied (use --upgrade to upgrade): python-jenkins==0.4.14 in /home/rbosak/.local/lib/python3.5/site-packages (from jenkins-cli==0.1.2)

...

copying build/lib/tests/test_cli.py -> /home/rbosak/.local/lib/python3.5/site-packages/tests
    byte-compiling /home/rbosak/.local/lib/python3.5/site-packages/jenkins_cli/cli_arguments.py to cli_arguments.cpython-35.pyc
    byte-compiling /home/rbosak/.local/lib/python3.5/site-packages/jenkins_cli/cli.py to cli.cpython-35.pyc
    byte-compiling /home/rbosak/.local/lib/python3.5/site-packages/jenkins_cli/version.py to version.cpython-35.pyc
    byte-compiling /home/rbosak/.local/lib/python3.5/site-packages/jenkins_cli/__init__.py to __init__.cpython-35.pyc
    byte-compiling /home/rbosak/.local/lib/python3.5/site-packages/tests/__init__.py to __init__.cpython-35.pyc
    byte-compiling /home/rbosak/.local/lib/python3.5/site-packages/tests/test_cli.py to test_cli.cpython-35.pyc
    running install_data
    copying contrib/bash-completion/jenkins -> /usr/share/bash-completion/completions
    error: could not create '/usr/share/bash-completion/completions/jenkins': Permission denied
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-2rmzm77_-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-0y1rkq6j-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-2rmzm77_-build/
```

The problem are the bash completion files, for copying which the user has no permissions.

I can workaround this by changing this in `setup.py`:

```python
for d in completion_dirs:
    if os.path.isdir(d):
        data_files.append((d, ['contrib/bash-completion/jenkins']))
```
to this
```python
for d in completion_dirs:
    if os.path.isdir(d):
        pass
```
This will, of course, install no bash completion files. 

Let me note that `sudo pip3 install something` is NOT recommended, at least not in Fedora linux. It can mess up your distro-provided packages.

**Comment by LD250** [comment]
I am not sure if it possible to setup bash completion files without sudo privileges.

**Comment by radomirbosak** [comment]
This might work, but I haven't tried it yet https://serverfault.com/a/506707

The other option is not to install them. Still better than fail with no explanation.

**Comment by LD250** [comment]
I have several thoughts about it:

1) When you installing package you still need ```sudo``` for most cases. The same is here, but we have pip for our package manager.

2) Adding to ```~/.bash_completion``` would be hard to maintain.

3) We can give an option "do not to install bash completion" or make a friendly warning if ```sudo``` is not used.

**Comment by radomirbosak** [comment]
I went with your option 3 in PR #40. Please take a look :)

I agree that option 2 could be tricky

Regarding point 1: I would say it's quite common to install pip packages as non-root (and for most packages it works fine).
