### ISSUE TITLE
submit first release to pypi

### ISSUE THREAD

**Issue by LD250** [LD250/jenkins-cli-python#8]

**Comment by LD250** [comment]
@bcicen , @muffinmad today I have submited first release to pypi. You can now `pip install jenkins-cli`

**Comment by muffinmad** [comment]
nice

**Comment by bcicen** [comment]
:+1: great!

fyi - you have a bit of a typo in the pip command under [installation](https://github.com/LD250/jenkins-cli-python#installation)
